package com.backend.playground.dao;

import java.sql.SQLException;
import java.util.List;

public interface IDao<T> {
    //TODO ESTA INTERFAZ TIENE LOS METODOS QUE DEBEN IMPLEMENTAR LAS CLASES QUE LA IMPLEMENTEN
    //TODO UTILIZAMOS GENERICS PARA QUE SEA UNA INTERFAZ GENERICA Y PUEDA SER IMPLEMENTADA POR DIFERENTES ENTIDADES
    //TODO DEBERAN SER LAS IMPLEMENTACIONES LAS QUE DEFINAN EL TIPO DE ENTIDAD QUE SE VA A MANEJAR
    //TODO EL METODO ELIMINAR ES UN VOID PORQUE NO RETORNA NADA, SOLO ELIMINA UN REGISTRO DE LA BASE DE DATOS POR ID
    //
    T registar(T t) throws SQLException;
    T buscarPorId(int id);

    void eliminarPorId(int id);

    List<T> buscarTodos();
}
